#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppDiaryHobbies.Resource", IsApplication=true)]

namespace AppDiaryHobbies
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int sectores_array = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int tipos_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06006a
			public const int btnAgregarCliente = 2131099754;
			
			// aapt resource value: 0x7f06006b
			public const int btnAgregarTarea = 2131099755;
			
			// aapt resource value: 0x7f06000a
			public const int btnAnadirCliente = 2131099658;
			
			// aapt resource value: 0x7f06001b
			public const int btnAnadirClienteDir = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int btnAnadirDireccion = 2131099678;
			
			// aapt resource value: 0x7f060077
			public const int btnAnadirEmpresa = 2131099767;
			
			// aapt resource value: 0x7f060079
			public const int btnAnadirTarea = 2131099769;
			
			// aapt resource value: 0x7f060078
			public const int btnAnadirUser = 2131099768;
			
			// aapt resource value: 0x7f060024
			public const int btnAnadirUsu = 2131099684;
			
			// aapt resource value: 0x7f060000
			public const int btnAtrasCliente = 2131099648;
			
			// aapt resource value: 0x7f060054
			public const int btnAtrasEmpresa = 2131099732;
			
			// aapt resource value: 0x7f060027
			public const int btnAtrasInfor = 2131099687;
			
			// aapt resource value: 0x7f06002f
			public const int btnAtrasLogueo = 2131099695;
			
			// aapt resource value: 0x7f060049
			public const int btnAtrasMod = 2131099721;
			
			// aapt resource value: 0x7f06006c
			public const int btnAtrasRegistro = 2131099756;
			
			// aapt resource value: 0x7f060022
			public const int btnAtrasUsers = 2131099682;
			
			// aapt resource value: 0x7f060037
			public const int btnBorrarTarea = 2131099703;
			
			// aapt resource value: 0x7f060025
			public const int btnBorrarUsu = 2131099685;
			
			// aapt resource value: 0x7f06003a
			public const int btnBorrarUsuario = 2131099706;
			
			// aapt resource value: 0x7f06002d
			public const int btnBuscarInforme = 2131099693;
			
			// aapt resource value: 0x7f06003b
			public const int btnCerrarModal = 2131099707;
			
			// aapt resource value: 0x7f060034
			public const int btnCerrarModalBorrar = 2131099700;
			
			// aapt resource value: 0x7f060038
			public const int btnCerrarModalBorrarUsu = 2131099704;
			
			// aapt resource value: 0x7f06007a
			public const int btnCerrarSesion = 2131099770;
			
			// aapt resource value: 0x7f060007
			public const int btnDialogFecha = 2131099655;
			
			// aapt resource value: 0x7f060033
			public const int btnLoguear = 2131099699;
			
			// aapt resource value: 0x7f060053
			public const int btnModificar = 2131099731;
			
			// aapt resource value: 0x7f060076
			public const int btnMuestraInformes = 2131099766;
			
			// aapt resource value: 0x7f06007b
			public const int btnPerfil = 2131099771;
			
			// aapt resource value: 0x7f060074
			public const int btnRegistrar = 2131099764;
			
			// aapt resource value: 0x7f06005b
			public const int btnRegistrarEmpresa = 2131099739;
			
			// aapt resource value: 0x7f06001f
			public const int btnTerminarTarea = 2131099679;
			
			// aapt resource value: 0x7f060068
			public const int btnVerMapa = 2131099752;
			
			// aapt resource value: 0x7f060018
			public const int btnVerMapaAnadirDir = 2131099672;
			
			// aapt resource value: 0x7f06008a
			public const int btnVolverAtras = 2131099786;
			
			// aapt resource value: 0x7f060092
			public const int imageView1 = 2131099794;
			
			// aapt resource value: 0x7f060014
			public const int lblDescTarea = 2131099668;
			
			// aapt resource value: 0x7f060082
			public const int lblDescripcionT = 2131099778;
			
			// aapt resource value: 0x7f060062
			public const int lblDescripcionTarea = 2131099746;
			
			// aapt resource value: 0x7f060066
			public const int lblDireccionActual = 2131099750;
			
			// aapt resource value: 0x7f060016
			public const int lblDireccionAnadir = 2131099670;
			
			// aapt resource value: 0x7f060088
			public const int lblDirecciones = 2131099784;
			
			// aapt resource value: 0x7f060086
			public const int lblHoraFin = 2131099782;
			
			// aapt resource value: 0x7f060084
			public const int lblHoraInicio = 2131099780;
			
			// aapt resource value: 0x7f06007e
			public const int lblNomT = 2131099774;
			
			// aapt resource value: 0x7f06000e
			public const int lblNomTarea = 2131099662;
			
			// aapt resource value: 0x7f06005e
			public const int lblNombreTarea = 2131099742;
			
			// aapt resource value: 0x7f060080
			public const int lblTipoT = 2131099776;
			
			// aapt resource value: 0x7f060011
			public const int lblTipoTar = 2131099665;
			
			// aapt resource value: 0x7f060060
			public const int lblTipoTarea = 2131099744;
			
			// aapt resource value: 0x7f060089
			public const int listaDirecciones = 2131099785;
			
			// aapt resource value: 0x7f06002e
			public const int listaInformes = 2131099694;
			
			// aapt resource value: 0x7f06007c
			public const int listaTareas = 2131099772;
			
			// aapt resource value: 0x7f060026
			public const int listaUsuarios = 2131099686;
			
			// aapt resource value: 0x7f060069
			public const int spClientes = 2131099753;
			
			// aapt resource value: 0x7f06002c
			public const int spClientesCascada = 2131099692;
			
			// aapt resource value: 0x7f06001a
			public const int spClientesDireccion = 2131099674;
			
			// aapt resource value: 0x7f060073
			public const int spEmpresas = 2131099763;
			
			// aapt resource value: 0x7f060052
			public const int spEmpresasMod = 2131099730;
			
			// aapt resource value: 0x7f06005a
			public const int spSector = 2131099738;
			
			// aapt resource value: 0x7f060036
			public const int spTareas = 2131099702;
			
			// aapt resource value: 0x7f060061
			public const int spTipoTarea = 2131099745;
			
			// aapt resource value: 0x7f060039
			public const int spUsuariosBorrar = 2131099705;
			
			// aapt resource value: 0x7f06002a
			public const int spUsuariosCascada = 2131099690;
			
			// aapt resource value: 0x7f06000c
			public const int tableLayout1 = 2131099660;
			
			// aapt resource value: 0x7f060064
			public const int tableLayout2 = 2131099748;
			
			// aapt resource value: 0x7f06001c
			public const int tableLayout3 = 2131099676;
			
			// aapt resource value: 0x7f06000d
			public const int tableRow1 = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int tableRow2 = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int tableRow3 = 2131099667;
			
			// aapt resource value: 0x7f060065
			public const int tableRow4 = 2131099749;
			
			// aapt resource value: 0x7f060043
			public const int tableRow5 = 2131099715;
			
			// aapt resource value: 0x7f06001d
			public const int tableRow7 = 2131099677;
			
			// aapt resource value: 0x7f060020
			public const int tableRow8 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int tableRow9 = 2131099681;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f06003d
			public const int textView10 = 2131099709;
			
			// aapt resource value: 0x7f06003f
			public const int textView11 = 2131099711;
			
			// aapt resource value: 0x7f060041
			public const int textView12 = 2131099713;
			
			// aapt resource value: 0x7f060019
			public const int textView14 = 2131099673;
			
			// aapt resource value: 0x7f060045
			public const int textView15 = 2131099717;
			
			// aapt resource value: 0x7f060047
			public const int textView16 = 2131099719;
			
			// aapt resource value: 0x7f060004
			public const int textView2 = 2131099652;
			
			// aapt resource value: 0x7f06003c
			public const int textView20 = 2131099708;
			
			// aapt resource value: 0x7f060006
			public const int textView3 = 2131099654;
			
			// aapt resource value: 0x7f060057
			public const int textView4 = 2131099735;
			
			// aapt resource value: 0x7f060008
			public const int textView5 = 2131099656;
			
			// aapt resource value: 0x7f06004f
			public const int textView6 = 2131099727;
			
			// aapt resource value: 0x7f060051
			public const int textView7 = 2131099729;
			
			// aapt resource value: 0x7f060083
			public const int txDescripcionT = 2131099779;
			
			// aapt resource value: 0x7f060015
			public const int txDescripcionTarea = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int txDireccionAnadir = 2131099671;
			
			// aapt resource value: 0x7f060087
			public const int txHoraFin = 2131099783;
			
			// aapt resource value: 0x7f060085
			public const int txHoraInicio = 2131099781;
			
			// aapt resource value: 0x7f06007d
			public const int txIdTarea = 2131099773;
			
			// aapt resource value: 0x7f06007f
			public const int txNomT = 2131099775;
			
			// aapt resource value: 0x7f06000f
			public const int txNomTarea = 2131099663;
			
			// aapt resource value: 0x7f060081
			public const int txTipoT = 2131099777;
			
			// aapt resource value: 0x7f060012
			public const int txTipoTarea = 2131099666;
			
			// aapt resource value: 0x7f060067
			public const int txtAddress = 2131099751;
			
			// aapt resource value: 0x7f060005
			public const int txtApellidosCliente = 2131099653;
			
			// aapt resource value: 0x7f060075
			public const int txtBienvenido = 2131099765;
			
			// aapt resource value: 0x7f060035
			public const int txtBorrarTitulo = 2131099701;
			
			// aapt resource value: 0x7f060058
			public const int txtCiudadEmpresa = 2131099736;
			
			// aapt resource value: 0x7f06002b
			public const int txtClientesBuscar = 2131099691;
			
			// aapt resource value: 0x7f060063
			public const int txtDescripcionTarea = 2131099747;
			
			// aapt resource value: 0x7f06008b
			public const int txtDireccionInf = 2131099787;
			
			// aapt resource value: 0x7f060046
			public const int txtEmpresaInfo = 2131099718;
			
			// aapt resource value: 0x7f060056
			public const int txtFuncion = 2131099734;
			
			// aapt resource value: 0x7f060023
			public const int txtGestionUsuarios = 2131099683;
			
			// aapt resource value: 0x7f06008d
			public const int txtHoraFinInf = 2131099789;
			
			// aapt resource value: 0x7f06008c
			public const int txtHoraInicioInf = 2131099788;
			
			// aapt resource value: 0x7f06008e
			public const int txtIdTareaList = 2131099790;
			
			// aapt resource value: 0x7f060028
			public const int txtInformesTitulo = 2131099688;
			
			// aapt resource value: 0x7f060093
			public const int txtLogueate = 2131099795;
			
			// aapt resource value: 0x7f060044
			public const int txtNickInfo = 2131099716;
			
			// aapt resource value: 0x7f060031
			public const int txtNickLoguear = 2131099697;
			
			// aapt resource value: 0x7f060090
			public const int txtNickUsuarioList = 2131099792;
			
			// aapt resource value: 0x7f06006e
			public const int txtNombre = 2131099758;
			
			// aapt resource value: 0x7f060003
			public const int txtNombreCliente = 2131099651;
			
			// aapt resource value: 0x7f060055
			public const int txtNombreEmpresa = 2131099733;
			
			// aapt resource value: 0x7f06003e
			public const int txtNombreInfo = 2131099710;
			
			// aapt resource value: 0x7f06004b
			public const int txtNombreMod = 2131099723;
			
			// aapt resource value: 0x7f06005f
			public const int txtNombreTarea = 2131099743;
			
			// aapt resource value: 0x7f06008f
			public const int txtNombreTareaList = 2131099791;
			
			// aapt resource value: 0x7f060072
			public const int txtPassword = 2131099762;
			
			// aapt resource value: 0x7f060032
			public const int txtPasswordLogueo = 2131099698;
			
			// aapt resource value: 0x7f060050
			public const int txtPasswordMod = 2131099728;
			
			// aapt resource value: 0x7f06006f
			public const int txtProfesion = 2131099759;
			
			// aapt resource value: 0x7f060040
			public const int txtProfesionInfo = 2131099712;
			
			// aapt resource value: 0x7f06004c
			public const int txtProfesionMod = 2131099724;
			
			// aapt resource value: 0x7f060048
			public const int txtRolInfo = 2131099720;
			
			// aapt resource value: 0x7f060091
			public const int txtRolUsuarioList = 2131099793;
			
			// aapt resource value: 0x7f060009
			public const int txtTelefonoCliente = 2131099657;
			
			// aapt resource value: 0x7f060059
			public const int txtTelefonoEmpresa = 2131099737;
			
			// aapt resource value: 0x7f06004d
			public const int txtTelefonoMod = 2131099725;
			
			// aapt resource value: 0x7f060042
			public const int txtTelefonoPerfil = 2131099714;
			
			// aapt resource value: 0x7f060070
			public const int txtTelefonoRegistro = 2131099760;
			
			// aapt resource value: 0x7f060001
			public const int txtTituloAnadeCliente = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int txtTituloAnadirDireccion = 2131099659;
			
			// aapt resource value: 0x7f060030
			public const int txtTituloApp = 2131099696;
			
			// aapt resource value: 0x7f06005d
			public const int txtTituloDatosTarea = 2131099741;
			
			// aapt resource value: 0x7f06004a
			public const int txtTituloModificar = 2131099722;
			
			// aapt resource value: 0x7f06005c
			public const int txtTituloNuevaTarea = 2131099740;
			
			// aapt resource value: 0x7f06006d
			public const int txtTituloRegistrar = 2131099757;
			
			// aapt resource value: 0x7f060071
			public const int txtUsuario = 2131099761;
			
			// aapt resource value: 0x7f060029
			public const int txtUsuarioBusca = 2131099689;
			
			// aapt resource value: 0x7f06004e
			public const int txtUsuarioMod = 2131099726;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LayoutAgregarCliente = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LayoutAnadirDireccion = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LayoutAnadirUsuario = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LayoutConsultaInformes = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LayoutLogueo = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LayoutModalBorrar = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LayoutModalBorrarUsuarios = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int LayoutModalPerfil = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int LayoutModificarUsuario = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int LayoutNuevaEmpresa = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int LayoutNuevaTarea = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int LayoutRegistro = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int LayoutTareasInicio = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int LayoutVerDatosTarea = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ListInformesDesign = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ListTareasDesign = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ListUsuariosDesign = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Main = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int main_txtTituloApp_text = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int main_txtTituloLogueo_text = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int main_txtTituloRegistro_text = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
